install:
    - rm -rf public  || exit 0  
    - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
    - sudo dpkg -i /tmp/hugo.deb
    
script:
    - hugo

branches:
    only:
        - master
  
deploy:
    provider: pages
    skip_cleanup: true
    local_dir: public
    keep-history: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
        branch: master