install:
    - rm -rf public  || exit 0
    
script:
    - ./hugo

branches:
    only:
        - master
  
deploy:
    provider: pages
    skip_cleanup: true
    local_dir: public
    keep-history: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
        branch: master