#baseURL = "https://www.manitowocmarineband.org/"
defaultContentLanguage = "en"
title = "Manitowoc Marine Band"
theme = "mmb"

[languages]
  [languages.en]
    locale = "en-US"

[services]
  [services.googleAnalytics]
    id = "UA-111647619-1"

[outputs]
  section = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true