backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
collections:
  - name: "events"
    label: "Event"
    folder: "content/event"
    filter:
      field: language
      value: en
    fields:
      - { name: "title", label: "Title" }
      - { name: "allday", label: "All Day?", widget: "boolean" }
      - { name: "startDate", label: "Start Time", widget: "datetime" }
      - { name: "endDate", label: "End Time", widget: "datetime" }
      - { name: "location", label: "Location" }
      - { name: "body", label: "Description", widget: "text" }
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads