name: Deploy to Github Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 0 1 1 *'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: build
        uses: docker://peaceiris/gha-hugo:latest
        with:
          args: --gc --cleanDestinationDir

      - name: deploy
        uses: docker://peaceiris/gh-pages:latest
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
      - name: Purge cache
        uses: docker://jakejarvis/cloudflare-purge-action:latest
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}

          
